### ISSUE TITLE
上部の検索解除が欲しい

### ISSUE THREAD

**Issue by mocomaruz** [volpe28v/DevHub#341]
入力があったら右端に×マークが登場して、×をクリックすると検索が解除される
![image](https://cloud.githubusercontent.com/assets/4833339/5610133/7b17d848-94f4-11e4-87d4-ab7a420aaac6.png)

... ような仕組みがあるといいな

**Comment by volpe28v** [comment]
自分も欲しいなぁとは思っていました。
本腰入れて調べますか・・・

**Comment by volpe28v** [comment]
この辺とか
http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q14109698164

**Comment by volpe28v** [comment]
あ、言い忘れましたが、issue初めありがとうございました！
