### ISSUE TITLE
app.jsonに環境変数を追記

### ISSUE THREAD

**Issue by hashrock** [volpe28v/DevHub#343]
app.jsonに環境変数を書いておくことで、
Heroku Buttonでのデプロイ時に、環境変数入力フォームを出すことが出来ます。

NODE_DEVHUB_USER、NODE_DEVHUB_PASSなどを指定しておくことで、
Heroku Buttonからでもbasic認証の設定が出来るなどして便利です。

ただし、この機能は簡易で便利ですが、ユーザのことを考えると、
設定値を環境変数ではなくDBに持ち、別途設定画面を用意したほうが
ベターかもしれません。

参考：
https://github.com/usutani/lodge_heroku_button/blob/heroku_button/app.json

**Comment by volpe28v** [comment]
DBに持った場合はパスワードなど設定後にすぐにBasic認証を設定することができますか？
サーバ起動時にしか設定できないと思い込んでいたのでその発想はありませんでした・・・。

**Comment by hashrock** [comment]
app.useを使った場合は、起動時にしか設定できなそうですね。大変失礼致しました。
調べた所、下記の書き方があるようです。

```
app.all('/admin', express.basicAuth(function (user, pass) {
    return user === 'admin' && pass === 'hoge';
}));
```

ここまでしか動作を確認していませんが、
固定文字列となっている部分をDBから読むようにすれば、
起動後でもパスワードを変更できそうです。

**Comment by volpe28v** [comment]
なるほどです。Setting ページなどにBASIC認証のIDとPASSを設定可能にしてあげればいつでも認証かけることが出来そうですね。
便利そうなのでトライしてみます！

**Comment by volpe28v** [comment]
とりあえず手っ取り早く app.json に環境変数の設定を加えてみました。

**Comment by volpe28v** [comment]
環境変数 NODE_DEVHUB_USER の命名が気になってきた・・・。 NODE_DEVHUB_ ってなんで付けたんだろう。
変えたくなってきた。
