### ISSUE TITLE
ファイル保存先にGridFSを使う

### ISSUE THREAD

**Issue by hashrock** [volpe28v/DevHub#344]
個人的な要望なので、fork作って実験する予定です。

herokuを使う場合、画像やファイルをアップロードしても、すぐ消えてしまいます。
MongoLabのSandboxプランでも500MBの容量があるため、GridFSを
保存先として使えるオプションがDevHubにあると便利な気がします。

一方、下記の懸案があります。
* 画像表示の速度低下
* 画像のキャッシュが効かなくなる

また、コードの複雑化が予想されますし、
別途VPSを借りれば解決する問題なので、欲しい人も少ないかもしれません。

**Comment by hashrock** [comment]
検証用ブランチ作りました。
Chromeにて画像とZIPのアップロード、アップロードファイル一覧、削除まで試しました。
想定漏れのケースがあるかもしれません。
https://github.com/hashrock/DevHub/tree/gridfs

DEMO（heroku上で画像の永続化）
https://devhub-gridfs.herokuapp.com/

あとは、コードの書き方を本体と合わせること、
通常のファイル保存と共存する仕組みが必要になります。

**Comment by volpe28v** [comment]
おぉ、これはすごい！
画像を mongodb に保存できるようになったんですね。

コードはまだちゃんと理解できていませんが(promise とか streamとかこうやって使うんだ。。)
ファイルシステムへの保存と代替可能であれば共存しなくても良いのかも？と思ってしまいました。

※DEMOの hashrockさんがアップロードしたファイルがリンク切れになっているのはなぜでしょう？

**Comment by hashrock** [comment]
あれ・・・消えてますね。
もうちょっと検証してみます！

**Comment by hashrock** [comment]
大変失礼しました・・・
間違ってmaster(つまりDBにファイルを保存してないバージョン)をDEMOとして動かしていました。
gridfsブランチをプッシュし直しましたので、お試しください。
時間がたってもファイルが消えなければ、ちゃんと動いているということになるかと思います。

共存についてですが、DevHubのmasterにこの機能をプッシュしてしまうと、
運用中のDevhubで、今までファイルアップロードした分が
アップロード一覧から見えなくなってしまう問題点があるのと、
herokuで使う以外のケースではこの機能は全く必要のないものなので、
変更の意義的にもどうかなぁと思うところがあります。

プラグインのようにして外部からこの機能を導入できると一番いいのかなぁと思ったりします。
ご意見お聞かせ頂けますと幸いです。

**Comment by volpe28v** [comment]
なるほど！対応ありがとうございます！　時間経ってますが大丈夫そうですね。

確かに既存のファイルへのリンクが切れてしまうのは問題ですね・・・。
完全に乗り換えてしまえば、バックアップなどもDBのみで済むので利便性は高まると思います。

現状のファイル達をDBにインポートする機能があればいいんですかねぇ。

**Comment by hashrock** [comment]
ご確認ありがとうございます！
確かにバックアップに使えそうですね。

DBにインポートする機能、作成できるか検討してみます！

**Comment by volpe28v** [comment]
ふと思ったのですが、今後新規に追加するファイルは /uploads 配下ではなくて、/uploads_db とかって別の名前にしてしまえば過去のアップロードファイルと共存できるのでは？と思いました。

**Comment by volpe28v** [comment]
すみません、やってみてわかりましたが、ディレクトリ変えてもファイル一覧に表示されない件は解決しないですね。。　見当違いな事言ってすみません！

参照なら過去の /uploads 配下に格納したファイルもちゃんと表示されるっぽいので、
gridFSへ移行した場合はファイル一覧を諦める、というのも一つの手かもしれないなぁと思いました。

なので、環境変数等でサーバ起動時にGridFSを有効化するか決められる方向で導入してみようかと思います。

**Comment by volpe28v** [comment]
GRIDFS=true で有効にしてみました。
Herokuでも画像使えるようになるので便利ですね！

**Comment by hashrock** [comment]
取り込み有難うございます！
herokuで使いやすくなりそうです！
