### ISSUE TITLE
チャット入力欄を文字数に合わせて広げたい

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/DevHub#345]
複数行に渡った時に自動的に伸縮したい。

不具合が無いか様子見

**Comment by mocomaruz** [comment]
close になったのかと思ってウヒョーとおもったら新規open でした.
そういえばissue あげてませんでした...

**Comment by volpe28v** [comment]
自分でも気になったので・・・。
それと、Winでも改行入れたいですねぇ。今は <br> でしのいでますが。

**Comment by volpe28v** [comment]
うーん、リサイズ系のプラグインをいろいろ試したけど上手くいかない・・・。
ちょっと保留。

**Comment by volpe28v** [comment]
フォーカスで autosize() を有効にしているが、アンフォーカス時にも入力途中のフォームサイズを維持したいので autosize() をキャンセルしなくていいかも。

**Comment by volpe28v** [comment]
Sendボタンを押しても発言してくれない場合がある。
続けて２回目を押すと発言できる。

**Comment by volpe28v** [comment]
手動でリサイズした場合にものすごくちっちゃくなる場合がある。

**Comment by volpe28v** [comment]
こんな感じで良さそうなので後で修正する。
![image](https://cloud.githubusercontent.com/assets/754962/5954801/ac9b9ae6-a7df-11e4-9272-14c203d6bc3d.png)

**Comment by volpe28v** [comment]
手動でリサイズできなくなったので不具合は発生しなくなった。
