### ISSUE TITLE
リファクタリングネタ

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/DevHub#357]
- [x] Setting の処理を別クラスへ
- [x] メモのデータバインディング出来るところをやる
- [x] cookie と localStorage の統一化
- [x] メモの更新時のデータ送受信を最小限にしたい

**Comment by mocomaruz** [comment]
?

**Comment by volpe28v** [comment]
リファクタリングネタをメモっとく issue として上げました。
機会を見てやろうかなと。

**Comment by mocomaruz** [comment]
いいですネ!
