### ISSUE TITLE
【不具合】firefox でテキストエリアが潰れる

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/DevHub#362]
Macのfirefox は大丈夫
Winのfirefoxでおかしかった

**Comment by dobachi** [comment]
CentOS6のFirefoxでもmessageのテキストエリアがつぶれていました。明示的にheightを指定したところ改善したためPRを送ります。

Windows8.1のFirefox、Chrome、IE、またCentOS6のFirefoxで確かめました。

修正前

![20150412_devhub_orig](https://cloud.githubusercontent.com/assets/4059356/7106450/51fb1c52-e17c-11e4-8333-07d8bc4c8282.png)

修正後

![20150413_devhub_new](https://cloud.githubusercontent.com/assets/4059356/7106451/5e7a3d50-e17c-11e4-886a-bf99b491456e.png)
