### ISSUE TITLE
マークダウンで水平線をサポート

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/DevHub#369]

**Comment by volpe28v** [comment]
-
--
---
----

**Comment by mocomaruz** [comment]
ハイフン3 連続以上で表示されました.
これは助かります!

![screen shot 2015-03-29 at 22 25 17](https://cloud.githubusercontent.com/assets/4833339/6885607/83e9b216-d662-11e4-9c4e-4c1e39ce62c6.jpg)

**Comment by volpe28v** [comment]
:+1:
