### ISSUE TITLE
オフライン時は分かるようにしたい

### ISSUE THREAD

**Issue by hashrock** [volpe28v/DevHub#407]
サーバを落としているのに気づかず、保存を行なうと
編集後の文章が消えてしまいます。

オフライン時は保存自体を押せないようにする、
もしくは編集後の文章が消えないようにならないでしょうか？

**Comment by volpe28v** [comment]
クライアントサイドでソケットが切れたら判定でければUIに反映出来そうですね。試してみます！

**Comment by volpe28v** [comment]
disconnect イベントは受けられるのでクライアントで判別可能ですね。
しかし、どのみち編集した内容を再接続時に反映するとなると複雑な仕組みになってしまいそうなので、
OFFLINEになっていることを画面上で注意喚起するのはいかがでしょう？
どう表現するかが難しいところですがｗ

**Comment by hashrock** [comment]
ご検討ありがとうございます。
それで十分かと思います！

Slackだと、reconnecting... のように再接続のステータスを表示してますね。

![2015-07-22 10 41 08](https://cloud.githubusercontent.com/assets/3132889/8816335/85eff4aa-3060-11e5-86f1-105bcbde17a5.png)

**Comment by volpe28v** [comment]
なるほど、さすが Slack ですね！　参考になります。
