### ISSUE TITLE
ブログ入力欄のサイズをブラウザからフォーカスが離れても維持したい

### ISSUE THREAD

**Issue by mocomaruz** [volpe28v/DevHub#414]
ブログ入力欄は、ディフォルト状態だと、ブラウザからフォーカスが離れた際に
自動的にシュリンクされてしまう。

外部のテキストなどからコピー・ペーストなどを行う際に、広がったり、縮まったりする
よりは、固定化されている方が入力しやすいかなと

任意に、サイズを変更した後だと、フォーカスが離れても縮まらない

![image](https://cloud.githubusercontent.com/assets/4833339/9350415/cb89520e-468b-11e5-8503-9dcbe2e1be7a.png)
ディフォルト状態

![image](https://cloud.githubusercontent.com/assets/4833339/9350423/df9431b0-468b-11e5-8562-b2d57887683c.png)
入力開始

![image](https://cloud.githubusercontent.com/assets/4833339/9350428/f112b57e-468b-11e5-9ec9-016b814691d5.png)
フォーカス外れると縮まっちゃう

**Comment by volpe28v** [comment]
たしかに余計なアニメーションですね。
最初は狭くても、文字量に応じて可変するのがいいかなと思います。
そのうち対応します！

**Comment by mocomaruz** [comment]
すみません。全く急がないですし優先度も高くないのですが
特に別のファイルとかからコピペしてると、うにうにするので(笑

**Comment by volpe28v** [comment]
・フォーカスで自動サイズ変更は無し
・入力に応じて行数が可変になるようにした
・フォームのサイズ変更は縦に固定
・Saveのボタンサイズを通常にした

とりあえずこんな感じでいかがでしょう。

**Comment by mocomaruz** [comment]
なんかすいません

**Comment by volpe28v** [comment]
いえいえ、空いた時間にやるのに丁度いいサイズのissueだったので^_^
