### ISSUE TITLE
ブログの[Save] ボタンを入力欄の右端のポジションに追従させたい

### ISSUE THREAD

**Issue by mocomaruz** [volpe28v/DevHub#415]
![image](https://cloud.githubusercontent.com/assets/4833339/9350676/b283d7b4-468d-11e5-8d48-d2e0cae67e2c.png)
ディフォルト位置

![image](https://cloud.githubusercontent.com/assets/4833339/9350686/bed0f290-468d-11e5-93c3-08526bd17134.png)
ウィンドウサイズに紐付いてるっぽいので、入力欄をでかくすると重なったり

![image](https://cloud.githubusercontent.com/assets/4833339/9350695/c92001fa-468d-11e5-9a59-5fd6f83dd626.png)
ウィンドウ広げると超横に行ったり

![image](https://cloud.githubusercontent.com/assets/4833339/9350769/68040154-468e-11e5-9655-3e295ca141d9.png)
このように入力欄が潜っている状態でウィンドウの下を入力欄と同じかそれよりも小さくすると...

![image](https://cloud.githubusercontent.com/assets/4833339/9350788/82712b16-468e-11e5-8371-9b0578c64264.png)
裏にいくなど

**Comment by volpe28v** [comment]
ブログの編集画面は仕様変更して上記画面が無くなったので close
