### ISSUE TITLE
grunt実行後のｍin.jsでエラー

### ISSUE THREAD

**Issue by hashrock** [volpe28v/DevHub#424]
DevHubの現masterをcloneして、DevHub_gruntを使ってmin.jsを作ったところ、
「Loading messages...」表示のまま、チャットのローディングが終わらなくなってしまいました。

Chromeのデベロッパーコンソールを見たところ、下記のエラーが出力されていました。

```
devhub.min.js:1 Uncaught ReferenceError: MessageDate is not defined
```

なお、もともと存在するmin.jsではこのエラーは起きていないようでした。

利用上問題はないので特に急いでいないですし、別ブランチでは治っているような気もするので、
気が向いたら見て頂けると幸いです。

**Comment by hashrock** [comment]
すみません！勘違いでした。
環境作りなおしたら、正常動作しました。
Closeさせて頂きます。

**Comment by volpe28v** [comment]
良かったです！
(最近 grunt メンテしてなかったのでドキッとしましたｗ)
