### ISSUE TITLE
実行ディレクトリによってuploadができない

### ISSUE THREAD

**Issue by hikefd** [volpe28v/DevHub#543]
initd-forever化して使わせていただいているところですが、
ファイルupload時に/tmpからのrenameコマンド等で宛先の./static/uploads/が無いと言われてappが落ちてしまいます
実行ディレクトリを指定すれば良いのかもしれませんが、app内で完結しているといいなと思いまして
力技ですが、相対参照をなんとかすべく./routes/upload.js内で以下のように対処しています

```
var staticUploadPath = __dirname.replace("routes","static/uploads");
- 中略 -
# var target_path = './static/uploads/' + file_name;
var targetPath = staticUploadPath + file_name;
- 他./static/uploads/指定部分を全てstaticUploadPathに-
```

何かかっこいい対処はありますでしょうか、的外れでしたらclose願います

**Comment by volpe28v** [comment]
issue に気づくのが遅くなって申し訳ありませんでした！
修正案、問題ないと思いますのでサンプルを参考に反映させていただきました。
(そもそも './static/uploads' が複数箇所にあるのもイケてなかったですねw )

**Comment by volpe28v** [comment]
＃相対パスで指定すると forever などで実行するとパスが合わないのか。。
＃他にも無いか心配。。
