### ISSUE TITLE
bundle.js を含めない構成にしたい

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/DevHub#554]
参考： https://github.com/hashrock/ganttpad/blob/master/package.json
"postinstall": "npm run build:js"

**Comment by hashrock** [comment]
Heroku上のpostinstallでビルドエラーが出る場合、
下記のページが参考になります！

http://qiita.com/verytired/items/0e600b96866867c0cb32

**Comment by volpe28v** [comment]
ありがとうございます！

結局jsのビルドは webpack を使うようにして、bundle.js をバージョン管理から外しました。

以下のコマンド役立ちました!
heroku config:set NPM_CONFIG_PRODUCTION=false --app
