### ISSUE TITLE
uploadsをファイルサイズ順にソートしたい

### ISSUE THREAD

**Issue by izumii19** [volpe28v/DevHub#582]
DevHub - uploadsをファイルサイズ順にソートしたい
DevHubを立てているVMのディスク容量がひっ迫してきたので、ファイルサイズの大きいものから削除したい。
そのためにファイルサイズ順にソートしたい

**Comment by volpe28v** [comment]
#583 で対応しました。問題なければクローズ願います！

**Comment by izumii19** [comment]
> #583 で対応しました。問題なければクローズ願います！

ありがとうございます！確認したらクローズしておきますので少々お待ち下さいー

**Comment by izumii19** [comment]
こちらも確認しましたー

**Comment by volpe28v** [comment]
ありがとうございますー！
