### ISSUE TITLE
uploadsで、削除しようとしたファイルがすでに削除済みだった場合にエラー吐いて死んでしまう

### ISSUE THREAD

**Issue by izumii19** [volpe28v/DevHub#584]
再現
1) 2人でそれぞれuploadsの画面を開いておく。
2) Aさんが”aaa.jpg”を削除
3) Bさんが”aaa.jpg”を削除（実体は削除済みなんだけど画面上にはまだ表示されているのでできちゃう）
4) おちた

実際に再現させたのは私じゃないんですが、このような現象が出たとのことでご報告でした。

**Comment by volpe28v** [comment]
おぉ、落ちちゃまずいですね。ガード処理入れておきます！

**Comment by volpe28v** [comment]
対応してみました！　落ちなくなったはず！

**Comment by izumii19** [comment]
> 対応してみました！　落ちなくなったはず！

素早い！
昨日のIssueとまとめて確認しておきますー

**Comment by volpe28v** [comment]
ありがとうございます。
全然急がないので超暇な時で良いですよ 😄

**Comment by izumii19** [comment]
Nさんがどこかのタイミングで社内Devhubに反映してくれると思うので、その後確認しておきますー

**Comment by izumii19** [comment]
社内Devhubを最新にアップデートしたので確認しました！

**Comment by volpe28v** [comment]
ありがとうございますー！
